apply plugin: 'com.gradleup.shadow'

apply from: "https://raw.githubusercontent.com/henkelmax/mod-gradle-scripts/${mod_gradle_script_version}/mod.gradle"

sourceSets {
    main {
        java {
            srcDir "${layout.buildDirectory.asFile.get()}/generated/java"
        }
    }
}

tasks.register('generateBuildConstants', Copy) {
    from 'src/template/java'
    into "${layout.buildDirectory.asFile.get()}/generated/java"
    expand 'compatibility_version': voicechat_compatibility_version,
            'mod_version': mod_version
}
compileJava.dependsOn generateBuildConstants

jar {
    manifest {
        attributes 'Main-Class': 'de.maxhenkel.voicechat.standalone.StandaloneServerMain'
    }
}

shadowJar {
    archiveClassifier.set('standalone')
    manifest {
        attributes 'Main-Class': 'de.maxhenkel.voicechat.standalone.StandaloneServerMain'
    }
}